
	
# Redirect for end-user’s browser preference override
[[redirects]]
  from = "/*"
  to = "/es-ES/:splat"
  status = 302
  conditions = {Language = ["es"]}

# Default
[[redirects]]
  from = "/*"
  to = "/en-GB/:splat"
  status = 200
